# Kapitel 2 – Ett ML-projekt från början till slut

Individuella övningsuppgifter.

> Arbeta fråga för fråga. Använd kurslitteraturen som primär referens och formulera svaren med egna ord.

In [88]:
# Gemensamma imports – fyll på vid behov
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Fråga 1

### I kapitlet beskrivs en checklista med sju steg. Beskriv de sju stegen översiktligt. Följs dessa steg linjärt eller arbetar man mer iterativt?

**Svar:**

De sju stegen är:

1. **Definiera problemet och skapa en helhetsbild** – förstå vad man faktiskt försöker lösa och vad målet är.
2. **Få tillgång till datan** – samla in eller hämta den data som behövs.
3. **Utforska datan och gör en EDA** – undersök datans struktur, kvalitet, samband och eventuella problem.
4. **Bearbeta datan** – exempelvis hantera saknade värden, kategorisk data och andra förberedelser.
5. **ML-modellering** – träna, jämföra och utvärdera modeller.
6. **Presentera lösningen för intressenter** – visa resultatet på ett sätt som är relevant och begripligt.
7. **Produktionssätt modellen och övervaka implementationen** – sätt modellen i faktisk användning och följ upp hur den fungerar.

I verkligheten arbetar man oftast iterativt snarare än att följa stegen helt linjärt. Man kan till exempel upptäcka problem under modelleringen som gör att man behöver gå tillbaka och bearbeta datan igen. Det togs upp flera praktiska exempel på detta under föreläsningar. Beroende på dataset måste man tvätta data, göra EDA, bearbeta, sen kanske man stannar i det här steget och itererar flera gånger innan man går vidare till modelleringen. I självaste modelleringssteget kan man behöva fortsätta bearbeta datan för att få bättre resultat. När man väl produktionssatt sin applikation behöver man sedan ha koll på att datan inte är föråldrad, korrupt mm. 

![image](./img_2/Skärmbild%202026-09-06%20182538.png)

## Fråga 2

### Vad menas med att en modell produktionssätts?

**Svar:**

Att **produktionssätta en modell** innebär att man tar modellen från utvecklingsmiljön och börjar använda den i ett riktigt system eller en applikation.

Det kan till exempel vara att koppla modellen till ett API (FastAPI ex), en webbapp eller ett system där den får ta emot riktig data och göra prediktioner eller vad man nu har utvecklat den till att göra.

Efter produktionssättning behöver modellen ofta också övervakas för att kontrollera att den fortsätter fungera bra över tid. Detta togs upp som ett exempel i ovanstående fråga, övervakningen kan exempelvis vara på själva datan eller att man ser över hallucinationer.

## Fråga 3

### Vad är scikit-learn för något? Vilka centrala designprinciper följer biblioteket? Vad är estimators, predictors och transformers?

**Svar:**

Scikit-learn är ett Python-bibliotek för ML. Det innehåller verktyg för bl.a modellträning, utvärdering och hyperparameter-tuning.

Biblioteket bygger på ett API, vilket gör att olika modeller & verktyg används på liknande sätt. Sekvensen rent kodmässigt brukar vara likadan för de olika modellerna enligt min uppfattning.

Några centrala designprinciper är:

- **Estimator** – ett objekt som lär sig från data, oftast genom .fit(). Detta används flitigt under modellträning under train-val-test
- **Predictor** – en estimator som kan göra prediktioner med exempelvis .predict(). Används lika flitigt under träningsstadiet av en modell
- **Transformer** – en estimator som omvandlar data med .transform(), ex. skalning eller encoding.

Det gör att många olika delar i scikit-learn följer samma typ av kodflöde::

`fit() -> transform()` eller `fit() -> predict()`

## Fråga 4

### Vad är TensorFlow och Keras?

**Svar:**

**TensorFlow** är ett ramverk för maskininlärning och deep learning.

**Keras** är ett enkelt API som används för att bygga neurala nätverk ovanpå TensorFlow.

Dessa ramverk har vi inte gått igenom under kursen, men misstänker att det kommer in senare när vi lär oss deep learning samt gruppuppgiften vi ska bygga.

## Fråga 5

### Vad säger du om Kalles och Stinas dialog?

**Svar:**

Stina har rätt. Testdatan ska användas först när modellen i princip är färdig, för att få en så korrekt slutlig utvärdering som möjligt.

Om Kalle fortsätter justera modellen utifrån resultatet på testdatan börjar han anpassa modellen efter testdatan (overfitting). Då förlorar testdelen av datan sitt syfte och resultatet kan se bättre ut än modellens förmåga att prediktera ny osedd data.

Justeringar bör istället göras utifrån tränings och valideringsdata.

## Fråga 6

### Många AI/ML-projekt når inte sina ursprungliga mål eller kommer aldrig längre än prototypstadiet. Vad tror du detta beror på och hur ska man förhålla sig till det?

**Svar:**

Det kan bero på flera saker, till exempel dålig datakvalitet, för lite data, otydliga mål eller att problemet visade sig vara svårare än man först trodde.

Därför är det viktigt att arbeta iterativt, testa tidigt och justera mål, data och behov under utvecklingen.

## Fråga 8

### Förklara vad koden gör. Varför är det viktigt att kunna spara en modell?

**Svar:**

Koden skapar först ett dataset och tränar en linjär regressionsmodell (model = LinearRegression().fit(X, y)) på datan.

Sedan sparas modellen till en fil med `dump()` och laddas tillbaka med `load()`. Den laddade modellen används därefter för att göra prediktioner.

Att kunna spara modellen är viktigt eftersom man då slipper träna om den varje gång den ska användas, till exempel i en applikation eller efter att programmet startats om.

## Fråga 9

### Läs in datasetet `data_01.csv` och genomför ett komplett regressionsflöde

In [89]:
# Imports

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import root_mean_squared_error

In [90]:
# Läs in datan

df = pd.read_csv("chapter_02_ml_project\data\data_01 (2).csv")

df.head()

<>:3: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\d'
C:\Users\chris\AppData\Local\Temp\ipykernel_9316\1975588539.py:3: SyntaxWarning: invalid escape sequence '\d'
  df = pd.read_csv("chapter_02_ml_project\data\data_01 (2).csv")

         x1        x2        x3        x4        x5      target
0  0.743487  1.072825  1.332911 -1.244771  0.344978  220.173943
1  0.835264  0.202184  0.966480  0.745883 -0.033773  175.873929
2 -1.103234  0.030615 -0.140385  0.727683 -2.831224 -162.270054
3  1.210186  1.685258 -0.394123  0.719024 -2.166585  165.930461
4  0.474577  0.647737 -0.451812 -0.409472 -0.051473   43.250511

In [91]:
# Få info om datasetet
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x1      199 non-null    float64
 1   x2      199 non-null    float64
 2   x3      199 non-null    float64
 3   x4      199 non-null    float64
 4   x5      199 non-null    float64
 5   target  199 non-null    float64
dtypes: float64(6)
memory usage: 9.5 KB

Datasetet innehåller fem features (`x1`–`x5`) och en target-kolumn. Därför används `target` som `y` och resterande kolumner som `X`.

In [92]:
# Vi definerar vår beroende och oberoende variabel. Tar bort target från X och assignar det till y

X = df.drop(columns="target")
y = df["target"]

X.head()

         x1        x2        x3        x4        x5
0  0.743487  1.072825  1.332911 -1.244771  0.344978
1  0.835264  0.202184  0.966480  0.745883 -0.033773
2 -1.103234  0.030615 -0.140385  0.727683 -2.831224
3  1.210186  1.685258 -0.394123  0.719024 -2.166585
4  0.474577  0.647737 -0.451812 -0.409472 -0.051473

In [93]:
# Dela upp vårt dataset i träningsdata och testdata

X_train_full, X_test, y_train_full, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Slutligen delar vi upp resterande observationer i valideringsdata,

X_train, X_val, y_train, y_val = train_test_split(
    X_train_full,
    y_train_full,
    test_size=0.15,
    random_state=42
)

# 68 % train
# 12 % validation
# 20 % test

In [94]:
# Träna två regressionsmodeller

linear_model = LinearRegression()
tree_model = DecisionTreeRegressor(random_state=42)

linear_model.fit(X_train, y_train)
tree_model.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

In [95]:
linear_pred = linear_model.predict(X_val)
tree_pred = tree_model.predict(X_val)

linear_rmse = root_mean_squared_error(y_val, linear_pred)
tree_rmse = root_mean_squared_error(y_val, tree_pred)

print("Linear Regression RMSE:", linear_rmse)
print("Decision Tree RMSE:", tree_rmse)

Linear Regression RMSE: 3.592300959691065
Decision Tree RMSE: 99.3594190386419

Linear Regression fick lägst RMSE och väljs därför som den bäst presterande modellen.

In [96]:
import pandas as pd

X_train_val = pd.concat([X_train, X_val])
y_train_val = pd.concat([y_train, y_val])

best_model = LinearRegression()
best_model.fit(X_train_val, y_train_val)

LinearRegression()

In [97]:
# Utvärdera modellen på testdatan

test_pred = best_model.predict(X_test)

test_rmse = root_mean_squared_error(y_test, test_pred)

print("Test RMSE:", test_rmse)

Test RMSE: 3.3715490775155477

In [98]:
# Träna om modellen på hela datasetet

final_model = LinearRegression()
final_model.fit(X, y)

LinearRegression()

Linear Regression presterade bäst av de två modellerna.

- Validation RMSE: `3.59`
- Test RMSE: `3.37`

Modellen tränades om på hela datasetet som slutlig modell. Den var överlägset bättre än beslutsträdet i det här exemplet.

# Fråga 10, 11 och 12

För att kunna se svar samt tillvägagångssätt till fråga 10, 11 och 12 i övningsuppgifterna hänvisar jag till filerna med namnen:

`mpg.ipynb` samt `salary.ipynb` i mappen för kapitel 2, mer specifikt `chapter_2_ml_project`.