## Fråga 11

### Arbeta med kategorisk data i `mpg`-datasetet

**Svar:**

Datasetet innehåller bland annat variablerna `origin` och `name`.

`origin` är kategorisk nominaldata (följer ingen naturlig ordning) och passar bra för dummy-variable-encoding

`name` har väldigt många unika värden och är inte relevant för att förutsäga bilens `mpg`, så den tas bort innan modelleringen.

In [7]:
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error

# Använder sns inbyggda exempeldataset

df = sns.load_dataset("mpg")

df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [8]:
# Tar bort saknade värden
df = df.dropna()

# Droppa kolumnen name
df = df.drop(columns="name")

# Printa ut 10 första kolumnerna
df.head(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa
5,15.0,8,429.0,198.0,4341,10.0,70,usa
6,14.0,8,454.0,220.0,4354,9.0,70,usa
7,14.0,8,440.0,215.0,4312,8.5,70,usa
8,14.0,8,455.0,225.0,4425,10.0,70,usa
9,15.0,8,390.0,190.0,3850,8.5,70,usa

In [9]:
# Vi gör en dummy encoding på origin kolumnen (sätter booleska värden på länderna bilarna kommer från)
df = pd.get_dummies(
    df,
    columns=["origin"],
    drop_first=True
)

# Printar ut första 5 cellerna i dataframen
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin_japan,origin_usa
0,18.0,8,307.0,130.0,3504,12.0,70,False,True
1,15.0,8,350.0,165.0,3693,11.5,70,False,True
2,18.0,8,318.0,150.0,3436,11.0,70,False,True
3,16.0,8,304.0,150.0,3433,12.0,70,False,True
4,17.0,8,302.0,140.0,3449,10.5,70,False,True

In [10]:
# Vi delar upp dataframen i X och y
X = df.drop(columns="mpg")
y = df["mpg"]

In [11]:
# Delar upp i tränings och testdata. 80/20
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [12]:
# Här tränar vi den linjära regressionsmodellen på träningsdatan och får ut RMSE

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

lin_reg_rmse = root_mean_squared_error(y_test, y_pred)

print("Test RMSE:", lin_reg_rmse)

Test RMSE: 3.256114096847396